### ISSUE TITLE
PHP Warning:  file_exists():

### ISSUE THREAD

**Issue by atiq4pk** [LotarProject/dokuwiki-template-bootstrap3#352] opened 2018-02-24 13:50 UTC
### Description

In the old version, I was not getting any PHP Warning, but now with new version (released on 2018-02-16), I am getting the following warning:
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/lib/tpl/bootstrap3/assets/fonts/flatly.fonts.css) is not within the allowed path(s): (/home/admin/web/MYDOMAIN.COM/public_html:/home/admin/tmp) in /home/admin/web/MYDOMAIN.COM/public_html/lib/tpl/bootstrap3/tpl_functions.php on line 1706, referer: http://www.MYDOMAIN.COM

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
It just appear after the upgrade to the template. With the same server and old version, I don't get any warning related to template. I have seen this on two different server running Apache.

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]: 2018-02-16
* [DokuWiki]: Release 2017-02-19e "Frusterick Manners"
* [Plugins]: 
* [Browser]: Any

### Screenshots or Logs

As in description.

### Sample page or snippet

It doesn't effect to any page view.

**Comment by LotarProject** [comment] 2018-02-25 21:19
Duplicate of #350

**Comment by LotarProject** [comment] 2018-02-25 22:12
Hi, This 8b809ea commit don't solve the issue but suppress the waning.

**Closed** 2018-03-02 11:24 UTC
Labels: bug
