### ISSUE TITLE
Dokuwiki-style pagetools no longer visible in responsive mode

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#105] opened 2015-10-19 17:19 UTC
Before they were out-of-view, and I would have to scroll to the right to see them. [Screenshot](https://ptpb.pw/VHLN.png)

Now they just aren't there.

**Comment by LotarProject** [comment] 2015-10-31 15:06
(marked as duplicate of #100)

**Closed** 2015-11-01 02:06 UTC
Labels: bug, duplicate
