### ISSUE TITLE
Change color of background in "Template-Design" settings does not apply

### ISSUE THREAD

**Issue by igittigitt** [LotarProject/dokuwiki-template-bootstrap3#297] opened 2017-03-07 13:06 UTC
### Description

Currently i use bootswatch.com theme "Cerulean". The background and page color is white but i want to have more contrast between them. So i want to have all page background to have an other color (unique grey) than the wikipage itself.

It seems that changes in the Temple-Design admin tool does not apply to bootswatch3 templates.

**Comment by LotarProject** [comment] 2017-12-23 01:12
Duplicate of #238

**Closed** 2018-01-05 00:51 UTC
