### ISSUE TITLE
Make Dokuwiki-style page tools available with fluidContainer.

### ISSUE THREAD

**Issue by per-hed** [LotarProject/dokuwiki-template-bootstrap3#123] opened 2015-11-17 14:12 UTC
Suggestion for an enhancement:

I like the Dokuwiki-style page tools, and it's great that you have added them to the template. However, as our install uses fluidContainer by default (and we are not considering activating the switchbutton) we miss out on this feature.

Would be nice if the page tools could be "squeezed in" between container and rightsidebar, as an option.

Thanks in advance!

**Comment by LotarProject** [comment] 2015-12-17 17:10
(marked as duplicate of #100)

**Closed** 2016-01-25 11:36 UTC
Labels: bug, duplicate, enhancement
