### ISSUE TITLE
Strange reaction for Anchor in Settings with menu tab

### ISSUE THREAD

**Issue by algorys** [LotarProject/dokuwiki-template-bootstrap3#248] opened 2016-09-06 08:30 UTC
### Description

If I'm in settings page (http://wiki.com/doku.php?id=accueil&do=admin&page=config) for the first time, when I clicked on a link in page menu, it'll no go to the correct place.

**Expected behavior:** Normally click on page menu give me to the choosen settings.

**Actual behavior:** Actually, if I click on a link in page menu, it will go randomly in settings page. It seems, it only appears at the first display of this page, when I reopen page menu and click again on a link, it works fine...
### Versions
- [Bootstrap3 Template] last one
- [DokuWiki] Elenor of sort.
- [Plugins] see screenshot below.
- [Browser] Chrome v53.0.2785.89 (on Linux)
### Screenshots
- If I click on TemplatePageName

![capture du 2016-09-06 10-26-32](https://cloud.githubusercontent.com/assets/8926922/18266745/77be2a0e-741c-11e6-93db-cf45e231a5e8.png)
- I go here...

![capture du 2016-09-06 10-26-50](https://cloud.githubusercontent.com/assets/8926922/18266790/94a0e594-741c-11e6-922d-067973cfaaad.png)

Thanks for help.

**Comment by Digitalin** [comment] 2016-09-07 07:30
Hi, 
I have noticed the same behaviour. It goes below the anchor, so need to scroll up to display the wanted section. 
A Lotar's Zen side, I guess : always let some imperfection in your art :smile:

**Comment by polyzen** [comment] 2016-09-07 07:49
Noted that as well:
* collapsing TOC causes contents to adjust and lose place
  * click item in TOC → collapse TOC → no longer where you wanted to be

**Comment by LotarProject** [comment] 2016-09-07 10:51
Hi! The problem is ``tocCollapseOnScroll`` config. During the scroll the TOC start closing and the page is automatically resized.

** Call for testing **

I have created a trigger for close the TOC after anchor click and before scrolling the page.
This patch is in dev branch.

**Comment by polyzen** [comment] 2016-09-10 05:11
Your fix does the job. :+1:

**Closed** 2016-11-07 18:55 UTC
Labels: bug, enhancement
